image: Visual Studio 2017
build_script:
  - ps: .\build.ps1
test:
  assemblies:
    - '**\*.Tests.dll'
test_script:
  - ps: .\tests.ps1
after_test:
  - ps: .\pack.ps1
artifacts:
  - path: '**\*.nupkg'