image: Visual Studio 2017

shallow_clone: true

branches:
  only:
  - master

skip_branch_with_pr: true

skip_tags: true

skip_commits:
  files:
  - LICENCE
  - README.md

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: .\build.ps1

test: off

deploy: 
  provider: NuGet
  api_key:
    secure: 9ss9qfvx79ig0btbd7ij9p4d
    artifact: /.*\.nupkg/

artifacts:
- path: artifacts/build
- path: artifacts/packages
- path: artifacts/test