image: Visual Studio 2017
build_script:
  - ps: .\build.ps1
test:
  assemblies:
    - '**\*.Tests.dll'
test_script:
  - ps: .\tests.ps1
after_test:
  - ps: .\pack.ps1
artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key: 
    secure: kyG+OoOaoRF4/dTPfLQ6KMWZLtAeWh8ssqSYZ7NE0mLlEzUE3sLOB37tzWEPFZs1
  skip_symbols: false
  artifact: /.*\.nupkg/
